apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: artists-db
  description: Stores artist details
  tags:
    - HTTP
    - TCP
    - Peering
    - Transig Gateway
    - SG
    - ALB
    - SSL/TLS
    - mTLS
    - Direct Connect
spec:
  type: database
  owner: team-a
  lifecycle: Provisionado
  system: artist-engagement-portal
