apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: artists-db
  description: Stores artist details
  tags:
    - http
    - tcp
    - peering
    - transig-gateway
    - sg
    - alb
    - ssl-tls
    - mtls
    - direct-connect
spec:
  type: Dados
  owner: team-a
  lifecycle: Provisionado
  system: artist-engagement-portal
