apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  # This is an extra long description with Markdown
  description: |
    [The Petstore](http://petstore.example.com) is an example API used to show features of the OpenAPI spec.
    - First item
    - Second item
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: "Serviço"
  lifecycle: Registrado
  owner: team-c
  providesApis:
    - petstore
    - streetlights
    - hello-world
    - teste-api-10
  consumesApi:
    - api:default/spotify
  partOf: ['component:artist-lookup']
