apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: servico-teste
  description: Componente de teste que consome uma API
  tags:
  - teste
  - api
spec:
  type: service
  lifecycle: Novo
  owner: team-a
  system: system:default/venda-rh
  consumesApis:
    - api:default/api-servico2
  dependsOn:
    - component:default/salesforce-ext
    - component:default/artist-lookup
