apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wayback-archive
  description: Archive of the wayback machine
  tags:
  - externo
spec:
  type: externo
  lifecycle: Ativo
  owner: team-a
  system: system:default/salesforce
  providesApis:
    - wayback-archive
  
