apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-servico2
  description: API de teste consumida por servico-teste
  tags:
  - lumis-token
  - rhsso-token
  - auth0-token
  - publico
  - privado
  - login-usuario
  - credentials
  - apikey
  - service-account
  - range-ips  
spec:
  type: openapi
  lifecycle: production
  owner: team-a
  definition:
    $text: ./petstore.oas.yaml
  consumedBy:
  - component:default/servico-teste

